### ISSUE TITLE
Posting coursework publically is not cool

### ISSUE THREAD

**Issue by Gregory-Bell** [zacatac/CS9G#2]
Please take down and make private this repo, and other repos containing university coursework,

Gregory Bell
Head Tutor, Self-Paced Center

**Comment by zacatac** [comment]
This coursework was completed as my first CS course at UCB. I had even forgotten that these were up, and they were posted years before the university began cracking down on code posted on Github. I'm happy to take it down, but maybe ask a little nicer next time.
